# Generated by Django 3.0.4 on 2020-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_chid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_cusid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
