# Generated by Django 3.0.4 on 2020-04-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200403_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_chid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stripe_cusid',
        ),
    ]
