# Generated by Django 3.0.4 on 2020-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200403_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentmode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
