# Generated by Django 3.0.4 on 2020-06-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
    ]
